import 'dart:core';

const String splashscreen = '/SplashScreen';
const String checkPhoneNumber = '/CheckPhoneNumber';
const String loginscreen = '/Login';
const String homescreen = '/HomeScreen';
const String verificationCodeScreen = '/VerificationCode';
const String passwordScreen = '/PasswordScreen';
const String marketPlaceScreen = '/MarketPlaceScreen';
const String bussinesCommunitiesScreen = '/BussinesCommunitiesScreen';
const String onlineStoreScreen = '/OnlineStoreScreen';
const String bussinesForSale = '/BussinesForSale';
const String tendersView = '/TendersView';
const String generalServiceView = '/GeneralServiceView';
const String investMentOpportunityView = '/InvestMentOpportunityView';
const String bussinesCommunityDetailPage = '/BussinesCommunityDetailPage';
const String tendersDetailPage = '/TendersDetailPage';
const String onlineStoreDetailPage = '/OnlineStoreDetailPage';
const String serviceDetailPage = '/ServiceDetailPage';
const String saleBussinesDetailPage = '/SaleBussinesDetailPage';
const String investmentDetailPage = '/InvestmentDetailPage';
const String inquiryScreen = '/InquiryScreen';
const String requestQuoteScreen = '/RequestQuoteScreen';
const String serviceinquiryScreen = '/ServiceSendInquiryScreen';
const String requestProposalScreen = '/RequestProposalScreen';
const String tenderResponseScreen = '/TenderResponseScreen';
const String procuremenetSoiScreen = '/ProcuremenetSoiScreen';
